### PR TITLE
Added test for checking engine and cache, tested against isssue

### LINKED ISSUE #19: Passing no cache with engine seems broken

### LINKED ISSUE #20: Update integration test to include engine

### PR DESCRIPTION
**Pull request by ddsmit**
Added integration test for the engine and cache. Everything seems to be working now, please pull down and test before release.

### CODE REVIEW

**Review by RichFoley — COMMENTED** [review]
Tested on the dash and got the same "bool is not callable" error

**Review by RichFoley — COMMENTED** [review]
Do we want to de-GKNify this file: /jinjaql/tests/run_GKN.py

**Comment by ddsmit** [comment]
Yes, I changed the naming from gkn to scratch, but forgot to rename the files. I'll fix when I dig into this later.

**Comment by ddsmit** [comment]
The issue reported was due to not changing the default behavior to reflect the change in the jinJAQL API. I updated how the jinJAQL object handles values passed so the default cache and engine will be used in a falsey value is passed (I will revert back the changes on the using library).
I see the new changes, not 100% sure if these carry into this pull request.

**Review by RichFoley — APPROVED** [review]

**Pull request merged**
